defaultUncompletedIconColor = "#FFFFFF"
defaultUncompletedTitleColor = "#7A7A7A"
defaultCompletedIconColor = "#009A0A"
defaultCompletedTitleColor = "#009A0A"
doAdvancementsBackgroundFade = true
showDebugCoordinates = false
orderTabsAlphabetically = false
#Values below 50% might give odd results, use on own risk ;)
#Range: 1 ~ 100
uiScaling = 100
#Lists the criteria for partially completed advancements, e.g. the biomes required for 'Adventuring Time'
#    Off: Vanilla default
#    Default: List which criteria you have already obtained
#    Spoiler: Only reveal unobtained criteria
#    All: Show both obtained and unobtained criteria
criteriaDetail = "Default"
criteriaDetailRequiresShift = false
addInventoryButton = true
defaultDrawDirectLines = false
defaultHideLines = false
defaultCompletedLineColor = "#009A0A"
defaultUncompletedLineColor = "#FFFFFF"
onlyUseAboveAdvancementTabs = true

